FROM openjdk:8-jdk-alpine
COPY target/dac-projeto-json-1.0-jar-with-dependencies.jar dac-projeto-json-1.0-jar-with-dependencies.jar
COPY json json
CMD ["java","-jar", "dac-projeto-json-1.0-jar-with-dependencies.jar"]